/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calculate_pi_NativeCalculatePi */

#ifndef _Included_com_calculate_pi_NativeCalculatePi
#define _Included_com_calculate_pi_NativeCalculatePi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_calculate_pi_NativeCalculatePi
 * Method:    calculatePi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_calculate_pi_CalculatePiService_calculatePi
  (JNIEnv *, jclass);

/*
 * Class:     com_calculate_pi_NativeCalculatePi
 * Method:    initCalculate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_calculate_pi_CalculatePiService_resetCalculateVariables
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
